[package]
name = "rust_yahoo_finance_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.28"
tokio-test = "0.4.3"
yahoo_finance_api = "2.0.1"
